import type { Metadata } from "next";
import "../../styles/_globals.scss";
import { ToastProvider } from "@/components";

export const metadata: Metadata = {
  title: "Som' Sweet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ToastProvider>
          {children}
        </ToastProvider>
      </body>
    </html>
  );

}
